version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1
jobs:
  build:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci

  release:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npx semantic-release

  'basic test':
    executor: cypress/base-12-14-0
    steps:
      # all dependencies were installed in previous job
      - attach_workspace:
          at: ~/
      - run:
          name: Netlify Build 🏗
          command: npx netlify build
          working_directory: tests/basic
          environment:
            DEBUG: netlify-plugin-cypress

  'recommended test':
    executor: cypress/base-12-14-0
    steps:
      # all dependencies were installed in previous job
      - attach_workspace:
          at: ~/
      - run:
          name: Netlify Build 🏗
          command: npx netlify build
          working_directory: tests/recommended
          environment:
            DEBUG: netlify-plugin-cypress

  'recording test':
    executor: cypress/base-12-14-0
    steps:
      # all dependencies were installed in previous job
      - attach_workspace:
          at: ~/
      - run:
          name: Netlify Build 🏗
          command: npx netlify build
          working_directory: tests/recording
          environment:
            DEBUG: netlify-plugin-cypress

  'test-twice':
    executor: cypress/base-12-14-0
    steps:
      # all dependencies were installed in previous job
      - attach_workspace:
          at: ~/
      - run:
          name: Netlify Build 🏗
          command: npx netlify build
          working_directory: tests/test-twice
          environment:
            DEBUG: netlify-plugin-cypress

  'test-prebuild-only':
    executor: cypress/base-12-14-0
    steps:
      # all dependencies were installed in previous job
      - attach_workspace:
          at: ~/
      - run:
          name: Netlify Build 🏗
          command: npx netlify build
          working_directory: tests/test-prebuild-only
          environment:
            DEBUG: netlify-plugin-cypress

  'test-using-chromium':
    executor: cypress/base-12-14-0
    steps:
      # all dependencies were installed in previous job
      - attach_workspace:
          at: ~/
      - run:
          name: Netlify Build 🏗
          command: npx netlify build
          working_directory: tests/use-chromium
          environment:
            DEBUG: netlify-plugin-cypress

  'test-netlify-dev':
    executor: cypress/base-12-14-0
    steps:
      # all dependencies were installed in previous job
      - attach_workspace:
          at: ~/
      - run:
          name: Netlify Build 🏗
          command: npx netlify build
          working_directory: tests/test-netlify-dev
          environment:
            DEBUG: netlify-plugin-cypress

  routing:
    executor: cypress/base-12-14-0
    steps:
      # all dependencies were installed in previous job
      - attach_workspace:
          at: ~/
      - run:
          name: Netlify Build 🏗
          command: npm run netlify:build
          working_directory: tests/routing
          environment:
            DEBUG: netlify-plugin-cypress

workflows:
  version: 2
  test_and_release:
    jobs:
      - build
      - cypress/install
      - 'basic test':
          requires:
            - cypress/install
      - 'recommended test':
          requires:
            - cypress/install
      - 'recording test':
          requires:
            - cypress/install
      - 'test-twice':
          requires:
            - cypress/install
      - 'test-prebuild-only':
          requires:
            - cypress/install
      - test-using-chromium:
          requires:
            - cypress/install
      - test-netlify-dev:
          requires:
            - cypress/install
      - routing:
          requires:
            - cypress/install
      - release:
          requires:
            - build
            - 'basic test'
            - 'recommended test'
            - 'recording test'
            - 'test-twice'
            - 'test-prebuild-only'
            - test-using-chromium
            - test-netlify-dev
            - 'routing'
          filters:
            branches:
              only:
                - master
                - beta
